#!/bin/bash
git config --global remote.origin.tagopt --tags
git config --global remote.origin.prune true
git config --global remote.origin.pruneTags true
git config --global push.followTags true
git config --global alias.tagm "!git tag \"$1\" -m \"version bump\" #"
